export { default as PersonalInfo } from './PersonalInfo/PersonalInfo'
export { default as FinishingUp } from './FinishingUp'
export { default as PickAddons } from './PickAddons'
export { default as SelectYourPlan } from './SelectYourPlan'
export { default as Sidebar } from './Sidebar/Sidebar'
export { default as Steps } from './Steps/Steps'
export { default as Summary } from './Summary'
